import "../styles/globals.css";

import LoginModal from "@/components/modals/LoginModal";
import AuthProvider from "@/providers/AuthProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tipey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoginModal />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
